name: "sotoweb"

networks:
  proxy-net:
    external: true

services:
  sotoweb-main:
    build: .
    container_name: sotoweb-main
    restart: unless-stopped
    environment:
      - DATABASE_URL=file:/app/db/prod.db
      - NEXT_PUBLIC_APP_URL=https://www.sotodelprior.com
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=https://sotodelprior.com
      - NEXTAUTH_SECRET=changeme123unused
    volumes:
      - ./db_data:/app/db
    networks:
      - proxy-net
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      # Router HTTPS
      - "traefik.http.routers.sotoweb-main.rule=Host(`sotodelprior.com`) || Host(`www.sotodelprior.com`)"
      - "traefik.http.routers.sotoweb-main.entrypoints=websecure"
      - "traefik.http.routers.sotoweb-main.tls=true"
      - "traefik.http.routers.sotoweb-main.tls.certresolver=le"
      # Servicio
      - "traefik.http.services.sotoweb-main.loadbalancer.server.port=3000"
      # Redirect HTTP -> HTTPS
      - "traefik.http.routers.sotoweb-main-http.rule=Host(`sotodelprior.com`) || Host(`www.sotodelprior.com`)"
      - "traefik.http.routers.sotoweb-main-http.entrypoints=web"
      - "traefik.http.routers.sotoweb-main-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
